default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1
joint_limits:
  JOINT1:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: false
    max_acceleration: 0.0
  JOINT2:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_position_limits: true
    min_position: -3.141593
    max_position: 0.10472
  JOINT3:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_position_limits: true
    min_position: -3.228859
    max_position: -0.087266
  JOINT4:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: false
    max_acceleration: 0.0
  JOINT5:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: false
    max_acceleration: 0.0
  JOINT6:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: false
    max_acceleration: 0.0
  JOINT7:
    has_velocity_limits: true
    max_velocity: 8.0
    has_acceleration_limits: false
    max_acceleration: 0.0
