moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - JOINT1
      - JOINT2
      - JOINT3
      - JOINT4
      - JOINT5
      - JOINT6

trajectory_execution:
  allowed_execution_duration_scaling: 20.0
  allowed_goal_duration_margin: 20.0
  allowed_start_tolerance: 0.10
  execution_duration_monitoring: false
