controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - JOINT1
      - JOINT2
      - JOINT3
      - JOINT4
      - JOINT5
      - JOINT6

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
